export const categories = [
  'Animal Welfare',
  'Arts & Heritage',
  'Children & Youth',
  'Community',
  'Education',
  'Elderly Aid',
  'Environment',
  'Health',
  'Special Needs',
  'Sports',
];

export const organizations = [
  'Action for Singapore Dogs',
  'Animal Concerns Research and Education Society',
  'Second Chance Animal Shelter',
  'Society for the Prevention of Cruelty to Animals (SPCA) ',
  'Beyond Social Services ',
  'Pathlight School',
  'People’s Association',
  'The Salvation Army, Singapore',
  'Youth Corps Singapore',
  'Babes Pregnancy Crisis Support Ltd (BABES)',
  'Make a Wish Foundation ',
  'Moral Welfare Home',
  'Yong En Care Centre ',
  'Ang Mo Kio Thye Hua Kwan Hospital',
  'Bright Vision Hospital',
  'Bethel Community Services',
  'Singapore Community Development Council (CDC)',
];
export const titles = [
  'Lorem ipsum dolor sit amet',
  'Proin id nisi nisi',
  ' Curabitur erat ligula',
  'Etiam suscipit feugiat dolor',
  'Sed eu massa nisl',
  'Vivamus non magna vel felis egestas dictum eget at dui',
  'Vestibulum dapibus porttitor nisl',
  'Duis sodales sollicitudin enim ut posuere',
  'Nunc felis ex, rhoncus eget diam vitae, blandit ullamcorper enim',
  'Aliquam in viverra dolor',
];
